fragment MenuParts on Menu {
  title
  body
  price
  type
  menu
}

fragment PropsParts on Props {
  title
  body
  link_text
  link_url
  image
  image_secondary
  image_third
  image_fourth
  image_alt
  image_bg
}

fragment StaffParts on Staff {
  title
  icon
  name
  body
  image
  order
}
